repos:
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      language_version: python3.7
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.2.3
    hooks:
    -   id: end-of-file-fixer
    -   id: flake8
    -   id: trailing-whitespace
        additional_dependencies: ["flake8-bugbear == 18.2.0"]
        language_version: python3.7
-   repo: https://github.com/asottile/pyupgrade
    rev: v1.2.0
    hooks:
    -   id: pyupgrade
