language: python
sudo: required
dist: xenial
python: "3.7"
#cache: pip
git:
  depth: 1
branches:
  except:
    - experimental
install:
  - pip install --pre -U tox
jobs:
  include:
    - stage: lint
      script: tox -e lint
    - stage: test
      script: tox -e test
