language: python
cache: pip
python:
 - "3.7"
git:
  depth: 10
branches:
  except:
    - experimental
install:
  - pip install --pre -U tox
jobs:
  include:
    - stage: lint
      script: tox -e lint
    - stage: test
      script: tox -e test
